language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sohampshetty/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sohampshetty/docker-react npm run test


